name: analyze and unit test

on:
  push:
    branches-ignore:
      - main
    paths:
      - "**.php"

jobs:
  phpstan:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 13306:3306
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: test
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
    env:
      DB_DATABASE: laravel
      DB_USER_NAME: root
      DB_PASSWORD: root

    environment: staging
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ReviewDogのセットアップ
      - name: Setup ReviewDog
        uses: reviewdog/action-setup@v1.0.3

      # PHP環境のセットアップ
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer, cs2pr
          coverage: xdebug

      - name: Composer install
        run: composer install

      # Databaseの設定
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env.staging');"

      # PRの差分ファイル名のみを抽出
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
            **/*.php
          separator: " "
          # 差分の比較先（マージ先のブランチを指定してください）
          base_sha: "main"

      - name: Run PHPStan
        run: vendor/bin/phpstan analyze

      - name: Remove 'laravel/' from paths
        id: remove-laravel-path
        run: |
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          modified_files=$(echo "$changed_files" | sed 's|laravel/||g')
          echo "Modified PHP files: $modified_files"
          echo "modified_files=$modified_files" >> "$GITHUB_OUTPUT"

      # PHPファイルが変更されていない場合は、PHPStanをスキップさせる
      - name: Check if PHP files have changed
        id: check-changed
        run: |
          if [ -z "${{ steps.remove-laravel-path.outputs.modified_files }}" ]; then
            echo "No PHP files have changed"
            echo "skip=true" >> "$GITHUB_OUTPUT"
          else
            echo "Changed PHP files: ${{ steps.remove-laravel-path.outputs.modified_files }}"
            echo "skip=false" >> "$GITHUB_OUTPUT"
          fi

      # PHPStan実行
      - name: Run PHPStan for Changed Files
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.ACTION_TOKEN }}
        if: ${{ steps.check-changed.outputs.skip == 'false' }}
        run: ./vendor/bin/phpstan analyze -c phpstan.neon --memory-limit=1G --error-format=raw --no-progress ${{ steps.remove-laravel-path.outputs.modified_files }} | reviewdog -reporter=github-pr-review -f=phpstan

      # PHP Unit実行
      - name: migrate
        run: php artisan migrate --force
        env:
          DB_HOST: 127.0.0.1

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --coverage-clover coverage.xml
        env:
          DB_HOST: 127.0.0.1

      - name: Run octocov
        uses: k1LoW/octocov-action@v0
